### ISSUE TITLE
Unit 2: audiogram_presby.jpg is displayed twice (2.30 and 2.34)

### ISSUE THREAD

**Issue by jamesthcheung** [MUTOR-2/ScienceOfMusic#1]
https://mutor-2.github.io/MUTOR/assets/images/audiogram_presby.jpg

I suspect that the wrong images are embedded for figures 2.30-2.31, judging from the alleged image source. The source points to our image [https://mutor-2.github.io/MUTOR/assets/images/audiogram_compared.gif], which is not included in the page (and therefore not redrawn). 

I think the correct images would be:
2.30: audiogram_compared.gif
2.31: audiogram.jpg
2:34: audiogram_presby.jpg

**Comment by maccallum** [comment]
yes, you're right, go ahead and make the change @cheungtszhim

**Comment by jamesthcheung** [comment]
Done
