### ISSUE TITLE
please reload the Youtube videos

### ISSUE THREAD

**Issue by fuxiao1208** [MUTOR-2/ScienceOfMusic#12]
Hi, 

I just replaced the four videos with copyright logo on youtube, please embed them on the webpage again, thank you

https://youtu.be/aAvR1vItpSI

https://youtu.be/WhSkYDLr3c4

https://youtu.be/pPJVGxKRcCE

https://youtu.be/bakZ1tWn-SY

**Comment by jamesthcheung** [comment]
Thanks!! Will do so shortly.

Did you delete the old videos on YouTube?

**Comment by jamesthcheung** [comment]
Updated
