### ISSUE TITLE
welcome text for The Science of Music

### ISSUE THREAD

**Issue by fuxiao1208** [MUTOR-2/ScienceOfMusic#13]
for this page :)
https://mutor-2.github.io/ScienceOfMusic/

This particular class is about The Science of Music: From the physics of sound generation to the cognitive abilities of humans to listen to music and to be moved by it.
It has a total of 12 units — each unit composed of a synopsis, specific content, quizzes and a section with references. A large number of images, animations, (interactive) audio and video examples are used within these units to make asynchronous and blended learning a pleasant experience. In these units, the focus is both on scientific research as well as the artistic application thereof. The materials are supplemented by Max patches (see www.cycling74.com).
Through the gradual learning of these units, you will get an overview of current practices in the fields of psychology of music and their application to multimedia composition. You will be able to competently discuss the impact of cognitive science on the understanding and appreciation of music and to gain insight into current research projects in these fields.

**Comment by dmuhr** [comment]
Done !
