### ISSUE TITLE
Unit 2: three images broken

### ISSUE THREAD

**Issue by maccallum** [MUTOR-2/ScienceOfMusic#2]
Figure 2.9: States of the Organ of Corti
The link used for this image is 
`https://mutor-2.github.io/MUTOR/assets/images/anatomy_organofcorti_states.png`, 
but the name of the file is 
`https://mutor-2.github.io/MUTOR/assets/images/organofcorti_states.png`.

It looks like you changed the name of the file for consistency, which is great, but just make a copy of the image in the old `/MUTOR` repository with the correct name so that it can be found on the new site.

Figure 2.18: Cranial Nerve VIII (auditory nerve in red)
The link is `https://mutor-2.github.io/ScienceOfMusic/units/02/anatomy_cranial8.png`, but the file has the `.png` extension duplicated: `anatomy_cranial8.png.png`.

Figure 2.34: Presbyacusis Audiogram
The link is `https://mutor-2.github.io/ScienceOfMusic/units/02/audiogram_presby.jpg`, but the file seems to be missing from the repo--maybe it didn't get checked in.

**Comment by jamesthcheung** [comment]
Thanks for checking! Yeah I was quite sleepy when I did this last night. Will fix it ;)

**Comment by jamesthcheung** [comment]
Fixed
