### ISSUE TITLE
Remove url from doi fields in references

### ISSUE THREAD

**Issue by maccallum** [MUTOR-2/ScienceOfMusic#9]
The `format_reference` include has been changed so that it expects a DOI without the server prepended to it. All `doi` fields in the references for the units should change from, for example 'https://doi.org/10.1159/000068999' to '10.1159/000068999'.

@cheungtszhim, I've assigned both of us--since you're working on the units now, if you want to add this to your list of things to do for each unit, that's cool, otherwise, I can do this once you're finished.

**Comment by jamesthcheung** [comment]
Ok!
